name: iOS Build & Distribute

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Distribute
    runs-on: macos-14 # Use the latest macOS with arm64 support
    permissions:
      contents: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Tuist
        uses: tuist/setup-tuist@v1

      - name: Install Tuist Dependencies
        run: tuist install

      - name: Generate Xcode Project
        run: tuist generate --no-open

      - name: Install Fastlane Plugins
        run: bundle exec fastlane install_plugins

      - name: Build and Distribute to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        run: bundle exec fastlane distribute
